### ISSUE TITLE
Unable to get the screenshot attached in the report on exception

### ISSUE THREAD

**Issue by pawankums** [cooperkong/ACucumberSpoonScreenshots#3]
hi, i want to take and embed the screenshot in the soon report whenever an exception occurs. But i am unable to do so as to take screenshot both the feature and scenario name is required. As i am running the tests through ./gradlew spoon command, its not executing the @After or @before annotation so that i can get the scenario reference to fetch the details.
Could you please let me know an example to take the screenshot and attach in the report on exception.

Thanks

**Comment by cooperkong** [comment]
hi @pawankums is the issue resolved?
